// Supabase Edge Function: admit-profile
// Returns an approximate "what it takes to get in" profile for a college:
// typical admitted GPA, course rigor, top extracurriculars that move the
// needle, and brief advice. Generated by OpenAI and cached in api_cache so
// repeat lookups are free.
//
// Body: { college: string, unitid?: number, state?: string }
// Returns: AdmitProfile
//
// Env vars: OPENAI_API_KEY

// deno-lint-ignore-file no-explicit-any
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { CORS, jsonResponse } from "../_shared/cors.ts";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SUPABASE_ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY")!;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const OPENAI_API_KEY = Deno.env.get("OPENAI_API_KEY");

const CACHE_TTL_DAYS = 90;

type ExtracurricularTip = {
  name: string;
  why: string;
};

type AdmitProfile = {
  college: string;
  unitid: number | null;
  gpa_avg: string | null;
  gpa_range: string | null;
  course_rigor: string | null;
  top_ecs: ExtracurricularTip[];
  advice: string | null;
  disclaimer: string;
  source: "openai" | "cache" | "unconfigured" | "no_match";
};

function cacheKeyFor(college: string, unitid?: number | null): string {
  if (unitid && Number.isFinite(unitid)) return `unitid:${unitid}`;
  return `name:${college.trim().toLowerCase().replace(/\s+/g, " ")}`;
}

async function generateWithOpenAI(
  college: string,
  state?: string,
): Promise<Omit<AdmitProfile, "source" | "unitid" | "disclaimer"> | null> {
  if (!OPENAI_API_KEY) return null;

  const locationHint = state ? ` (${state})` : "";
  const prompt = `You advise high school students on US college admissions.

For "${college}"${locationHint}, return an APPROXIMATE typical admitted-student profile
based on publicly reported Common Data Set figures and reputable college-counseling
sources. If the school is open-admission or highly nonselective, return modest
numbers and say so in the advice. Do NOT fabricate exact statistics — give realistic
ranges and round numbers.

Return ONLY valid JSON in this exact shape, no prose:
{
  "gpa_avg": "3.85"          // unweighted average GPA of admitted students, as a string with 2 decimals
                              // use null if you genuinely don't know
  "gpa_range": "3.7 - 4.0",  // unweighted middle-50 range
  "course_rigor": "string",   // one sentence on coursework expected (APs, IB, dual enrollment)
  "top_ecs": [                // 5 extracurricular themes that meaningfully boost an applicant
    {"name": "concise theme", "why": "one sentence on why admissions cares"}
  ],
  "advice": "2-3 sentences of the most impactful guidance for someone aiming here"
}`;

  const res = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${OPENAI_API_KEY}`,
    },
    body: JSON.stringify({
      model: "gpt-4o-mini",
      response_format: { type: "json_object" },
      messages: [
        {
          role: "system",
          content:
            "You output strict JSON only. Be honest about uncertainty — use null or ranges rather than inventing precise numbers.",
        },
        { role: "user", content: prompt },
      ],
    }),
  });
  if (!res.ok) return null;
  const json = await res.json();
  const content = json?.choices?.[0]?.message?.content;
  if (!content) return null;
  try {
    const parsed = JSON.parse(content);
    const ecs = Array.isArray(parsed?.top_ecs) ? parsed.top_ecs : [];
    return {
      college,
      gpa_avg: typeof parsed?.gpa_avg === "string" ? parsed.gpa_avg : null,
      gpa_range:
        typeof parsed?.gpa_range === "string" ? parsed.gpa_range : null,
      course_rigor:
        typeof parsed?.course_rigor === "string" ? parsed.course_rigor : null,
      top_ecs: ecs
        .map((e: any) => ({
          name: typeof e?.name === "string" ? e.name : "",
          why: typeof e?.why === "string" ? e.why : "",
        }))
        .filter((e: ExtracurricularTip) => e.name)
        .slice(0, 6),
      advice: typeof parsed?.advice === "string" ? parsed.advice : null,
    };
  } catch {
    return null;
  }
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: CORS });
  if (req.method !== "POST")
    return jsonResponse({ error: "method not allowed" }, 405);

  const authHeader = req.headers.get("Authorization");
  if (!authHeader) return jsonResponse({ error: "missing auth" }, 401);

  const userClient = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: authHeader } },
  });
  const { data: userData, error: userErr } = await userClient.auth.getUser();
  if (userErr || !userData.user)
    return jsonResponse({ error: "unauthorized" }, 401);

  let body: { college?: string; unitid?: number; state?: string };
  try {
    body = await req.json();
  } catch {
    return jsonResponse({ error: "bad json" }, 400);
  }

  const college = (body.college ?? "").toString().trim();
  if (!college) return jsonResponse({ error: "missing college" }, 400);

  const unitid =
    typeof body.unitid === "number" && Number.isFinite(body.unitid)
      ? body.unitid
      : null;
  const state = typeof body.state === "string" ? body.state : undefined;

  const disclaimer =
    "Approximate. Generated from public data and counseling guidance — verify on the college's own admissions page.";

  if (!OPENAI_API_KEY) {
    return jsonResponse({
      college,
      unitid,
      gpa_avg: null,
      gpa_range: null,
      course_rigor: null,
      top_ecs: [],
      advice: null,
      disclaimer,
      source: "unconfigured",
    } satisfies AdmitProfile);
  }

  const admin = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
  const cacheKey = cacheKeyFor(college, unitid);

  const cached = await admin
    .from("api_cache")
    .select("payload, fetched_at")
    .eq("provider", "admit_profile")
    .eq("cache_key", cacheKey)
    .maybeSingle();

  const fresh =
    cached.data &&
    Date.now() - new Date(cached.data.fetched_at).getTime() <
      CACHE_TTL_DAYS * 86_400_000;

  if (fresh && cached.data) {
    return jsonResponse({
      ...(cached.data.payload as Record<string, unknown>),
      unitid,
      disclaimer,
      source: "cache",
    } as AdmitProfile);
  }

  const generated = await generateWithOpenAI(college, state);
  if (!generated) {
    return jsonResponse({
      college,
      unitid,
      gpa_avg: null,
      gpa_range: null,
      course_rigor: null,
      top_ecs: [],
      advice: null,
      disclaimer,
      source: "no_match",
    } satisfies AdmitProfile);
  }

  await admin.from("api_cache").upsert(
    {
      provider: "admit_profile",
      cache_key: cacheKey,
      payload: generated,
      fetched_at: new Date().toISOString(),
    },
    { onConflict: "provider,cache_key" },
  );

  return jsonResponse({
    ...generated,
    unitid,
    disclaimer,
    source: "openai",
  } satisfies AdmitProfile);
});
